# Julia Syntax Tutorial

Everything covered today (and **even more**) can be found [here](https://docs.julialang.org/en/v1/). Code in this notebook has been tested to be compatible with Julia 1.2.0. 

The way to use a package is: 

In [15]:
using LinearAlgebra

First, let's take a look at how to create variables.

In [8]:
x = 3 
x = 3.0
words = "Hello world!"
character = 'a'
δ = 1e-5
pi
MathConstants.e
α̂₁ = pi / 2

1.5707963267948966

Then, the arrays.

In [19]:
u = [1 3 5 7]
v = ones(4)
w = Vector{Float64}(undef, 2)

X = rand(4, 4)
Identity_matrix = Matrix{Float64}(I, 4, 4)
column = [1,2,3]
row = [1 2 3]
A = [1 2 3; 4 5 6; 7 8 9]
b = [[1 2 3] [4 5 6] [7 8 9]]
B = reshape(b, 3, 3)
C = fill(15, 2, 3)

length(A)
ndims(A)
size(A)


(3, 3)

In [26]:
A

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

Array indexing and assignment

In [31]:
A[3, 1]
A[1, :]
A[1:2, 2:end]
A[2, [1 3]]

A[2, 3] = 10
A[3, 1:2] = [-2 -3]

1×2 Array{Int64,2}:
 -2  -3

In [32]:
A

3×3 Array{Int64,2}:
  1   2   3
  4   5  10
 -2  -3   9

In [33]:
# Mathematical operations

2 + 5
3.5 ^ 2
[1 2] + [2 3]
[1 2] * 1.5
A[1, :]' * ones(3)
A .* B

3×3 Array{Int64,2}:
  1    8  21
  8   25  80
 -6  -18  81

In [34]:
A

3×3 Array{Int64,2}:
  1   2   3
  4   5  10
 -2  -3   9

In [35]:
B

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [38]:
3.0 > 2.0
9 ≤ 9
1 != 2
[1 2] .< [2 3]

1×2 BitArray{2}:
 1  1

Control flow

In [39]:
x = 2
y = 1
if x < y
    println("x is less than y: $x < $y")
elseif x > y
  println("x is greater than y: $x > $y")
else
  println("x is equal to y: $x = $y")
end

x is greater than y: 2 > 1


In [40]:
i = 1
while i <= 5
    println(i)
    i += 1 
end

1
2
3
4
5


In [41]:
for i = 1:5
    if i == 3
        continue
        #break
    end
    println(i)
end

1
2
4
5


In [42]:
u = [1,3,5,7]
for i in u
    println(i)
end

1
3
5
7


# functions

The following three syntaxes all define the function f(x) = 2x:

In [43]:
f(x) = 2*x
function f(x)
    return 2*x
end

f (generic function with 1 method)

In [44]:
# default values for positional arguments
function f(x, mult=2)
    return mult*x
end
f(2)    # ==4
f(2, 3) # ==6

6

In [45]:
# default values for keyword arguments: use a semicolon instead of a comma
function f(x; mult=2)
    return mult*x
end
f(2)         # ==4
f(2, mult=3) # ==6

6

In [46]:
# a changeable number of arguments
function f(x...)
    for xi in x
        println(xi)
    end
end
f(1,2,3,4,"a","b","c")

1
2
3
4
a
b
c


In [47]:
# list comprehensions: shorthand for loops (not very memory efficient)
[x^2 for x in 1:5]
[x^2 for x in 1:5 if x>2]
[x^k for x in 1:10 for k in 1:5]

50-element Array{Int64,1}:
      1
      1
      1
      1
      1
      2
      4
      8
     16
     32
      3
      9
     27
      ⋮
   4096
  32768
      9
     81
    729
   6561
  59049
     10
    100
   1000
  10000
 100000

In [48]:
# dictionaries and sets

x = Set([1,2,3,3,4,1])
d = Dict()
d[4] = 7
# XXX add more here

7

# advanced topic for people who like object-oriented programming: types and multiple dispatch

In [49]:
# x::y is an assertion that x is a variable of type y
1.0::Float64

1.0

In [50]:
# if we assert something false, we get a type error 
1.0::Int

TypeError: TypeError: in typeassert, expected Int64, got Float64

In [51]:
# we can define many functions with the same name, which call arguments of different types
# julia decides which to call by looking at the type of the argument

f(x::Int) = println("$x is an integer")
f(x::Float64) = println("$x is an float")
f(2)
f(2.0)

2 is an integer
2.0 is an float


We may define a composite type as follows:

In [56]:
struct Student
    name::String    
    gpa::Float64
end

In [57]:
s1 = Student("Alice", 3.9)
s2 = Student("Bob", 3.2)

Student("Bob", 3.2)

In [59]:
s1.name

"Alice"

In [60]:
f(s::Student) = println("$(s.name) has a $(s.gpa) gpa")

# we've defined the "f" function on three different types
# julia knows to call the write one by looking at the type of the argument

f(s1)
f(s2)
f(4)
f(sqrt(2))

Alice has a 3.9 gpa
Bob has a 3.2 gpa
4 is an integer
1.4142135623730951 is an float
