In [2]:
import numpy as np

In [3]:
# generate random data matrix
n,d = 6,4
X = np.random.randn(n,d)

In [4]:
# optional: give it linearly dependent columns
# X[:,2] = X[:,1]

## Understanding the pseudoinverse

In [5]:
# form pseudoinverse
Xd = np.linalg.pinv(X)

In [6]:
# X†X ≈ I_d
np.dot(Xd,X)
np.matmul(Xd,X)

array([[  1.00000000e+00,   3.12250226e-17,  -5.11743425e-17,
         -1.80411242e-16],
       [ -6.66133815e-16,   1.00000000e+00,  -5.55111512e-16,
         -2.22044605e-16],
       [ -2.77555756e-17,  -2.06432094e-16,   1.00000000e+00,
          1.11022302e-16],
       [  2.22044605e-16,   1.11022302e-16,   8.32667268e-17,
          1.00000000e+00]])

In [7]:
# XX† !≈ I_n
np.dot(X,Xd)

array([[ 0.98360287,  0.12248737,  0.01886647,  0.02005777,  0.01662301,
         0.00951475],
       [ 0.12248737,  0.03548311, -0.05883995,  0.04165927, -0.06905991,
        -0.09619771],
       [ 0.01886647, -0.05883995,  0.84222775, -0.3404634 , -0.11047551,
         0.03069059],
       [ 0.02005777,  0.04165927, -0.3404634 ,  0.23513016, -0.23341564,
         0.08548665],
       [ 0.01662301, -0.06905991, -0.11047551, -0.23341564,  0.92181927,
         0.01830867],
       [ 0.00951475, -0.09619771,  0.03069059,  0.08548665,  0.01830867,
         0.98173684]])

In [8]:
Q,R = np.linalg.qr(X)

In [9]:
Q

array([[-0.80793942, -0.49084466,  0.16273748, -0.2518428 ],
       [-0.0647065 , -0.03940912,  0.11818432, -0.12560083],
       [-0.19058588,  0.13394586, -0.84535442, -0.2708121 ],
       [-0.07355343,  0.19707139,  0.43373535,  0.05250301],
       [ 0.26122546, -0.77066799, -0.20040447,  0.46849698],
       [-0.48277856,  0.326819  , -0.12898288,  0.79070504]])

In [10]:
R

array([[-3.13634085,  0.97987361, -0.99422615, -0.19898412],
       [ 0.        , -1.75140275,  1.20554948,  1.74043898],
       [ 0.        ,  0.        ,  1.11948714, -0.22360831],
       [ 0.        ,  0.        ,  0.        , -3.11367904]])

In [11]:
np.dot(np.transpose(Q),Q)

array([[  1.00000000e+00,  -3.54399873e-17,   3.59591080e-17,
         -6.72603615e-17],
       [ -3.54399873e-17,   1.00000000e+00,   1.30071649e-16,
         -7.57974982e-17],
       [  3.59591080e-17,   1.30071649e-16,   1.00000000e+00,
         -7.08979630e-17],
       [ -6.72603615e-17,  -7.57974982e-17,  -7.08979630e-17,
          1.00000000e+00]])

In [12]:
# form data from noisy linear model
wn = np.random.randn(d)
y = np.dot(X,wn) + .1*np.random.randn(n)

In [13]:
# solve least squares problem to estimate w
w,resid,rank,s = np.linalg.lstsq(R,np.dot(np.transpose(Q),y))

In [14]:
# how good is our estimate?
np.linalg.norm(w - wn)

0.056414437291891842

In [15]:
# compute mean square error
np.mean((y - np.dot(X,w))**2)

0.0013961988896388216

In [16]:
# let's use the shorthand
w_backslash,resid,rank,s = np.linalg.lstsq(X,y)
np.linalg.norm(w_backslash - w)

9.3590220573910122e-16

In [17]:
w_backslash

array([-0.10513049,  1.58268384,  2.13643905,  0.85134259])