In [14]:
import numpy as np

In [15]:
# generate random data matrix
n,d = 6,4
X = np.random.randn(n,d)

In [16]:
# optional: give it linearly dependent columns
#X[:,2] = X[:,1]

In [17]:
U,sigma,V = np.linalg.svd(X, full_matrices=0) # M = 6, N = 4

In [18]:
np.dot(np.transpose(U),U)

array([[  1.00000000e+00,   2.84790810e-16,   3.20260468e-17,
          1.08370681e-16],
       [  2.84790810e-16,   1.00000000e+00,   2.80902230e-16,
          2.47045532e-17],
       [  3.20260468e-17,   2.80902230e-16,   1.00000000e+00,
          2.28063581e-17],
       [  1.08370681e-16,   2.47045532e-17,   2.28063581e-17,
          1.00000000e+00]])

In [19]:
np.dot(np.transpose(V),V)

array([[  1.00000000e+00,   0.00000000e+00,  -2.77555756e-17,
         -1.94289029e-16],
       [  0.00000000e+00,   1.00000000e+00,  -8.32667268e-17,
          0.00000000e+00],
       [ -2.77555756e-17,  -8.32667268e-17,   1.00000000e+00,
         -1.66533454e-16],
       [ -1.94289029e-16,   0.00000000e+00,  -1.66533454e-16,
          1.00000000e+00]])

In [20]:
sigma

array([ 3.87963681,  2.03238934,  1.35163362,  0.32659539])

In [21]:
# decomposition is just as good if we ignore the 0 in sigma and reduce r by 1
np.linalg.norm(X - np.dot(np.dot(U[:,0:3],np.diag(sigma[0:3])),np.transpose(V[:,0:3])))

4.683452852778931

In [22]:
# form data from noisy linear model
wn = np.random.randn(d)
y = np.dot(X,wn) + .1*np.random.randn(n)

In [23]:
# solve least squares problem to estimate w
w = np.dot(np.dot(np.dot(V,np.diag(sigma**(-1))),np.transpose(U)),y)
# w = np.dot(np.dot(np.dot(V[:,0:3],np.diag(sigma[0:3]**(-1))),np.transpose(U[:,0:3])),y)

In [24]:
# how good is our estimate?
np.linalg.norm(w - wn)

0.43690075966676073

In [25]:
# compute mean square error
np.mean((y - np.dot(X,w))**2)

0.32304866154405798

In [26]:
# let's use the shorthand
w_backslash,resid,rank,s = np.linalg.lstsq(X,y)
np.linalg.norm(w_backslash - w)

0.69744648139829368